
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootexample?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

mybatis:
  type-aliases-package: com.fdd.bean